const CardContent = [
  {
    title: "ps",
    name: "Photoshop",
    year: "2023",
    v: ["24.6.0.573"],
    link: ["https://www.google.com"],
  },
  {
    title: "ai",
    name: "Illustrator",
    year: "2023",
    v: ["27.6.1.210"],
    link: ["https://www.google.com"],
  },
  {
    title: "ae",
    name: "AfterEffects",
    year: "2023",
    v: ["23.5.0.52"],
    link: ["https://www.google.com"],
  },
  {
    title: "xd",
    name: "XD",
    year: "2023",
    v: ["57.0.12"],
    link: ["https://www.google.com"],
  },
  {
    title: "pr",
    name: "PremierePro",
    year: "2023",
    v: ["23.5.0.56"],
    link: ["https://www.google.com"],
  },
  {
    title: "wtf",
    name: "very fucking long title that never ends hahah ahahahah ahahaha hahaha",
    year: "2023",
    v: ["23.5.0.56"],
    link: ["https://www.google.com"],
  },
  {
    title: "id",
    name: "Indesign",
    year: "2023",
    v: ["18.3.0.50"],
    link: ["https://www.google.com"],
  },
  {
    title: "me",
    name: "Media Encoder",
    year: "2023",
    v: ["23.5.0.51"],
    link: ["https://www.google.com"],
  },
  {
    title: "au",
    name: "Audition",
    year: "2023",
    v: ["23.5.0.48"],
    link: ["https://www.google.com"],
  },
  {
    title: "an",
    name: "Animate",
    year: "2023",
    v: ["23.0.2.103"],
    link: ["https://www.google.com"],
  },
  {
    title: "off",
    name: "Office",
    year: "2021",
    v: ["ProfessionalPlus"],
    link: ["https://www.google.com"],
  },
  {
    title: "win10",
    name: "Windows",
    year: "2023",
    v: ["19045.2965"],
    link: ["https://www.google.com"],
  },
];

export { CardContent };
